# Generated by Django 4.1.7 on 2023-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_certificate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
